#!/usr/bin/env python3
"""Generate AQI condition SVGs and portable GTK3 CSS (stdlib only).

Concept: a soft "air puff" cloud whose tint follows the EPA colour scale and
whose particle count rises with severity, so category reads at 24px even
before the number does. Colours match aqi.sh color_for (Catppuccin Mocha).
Re-run after editing: python3 scripts/aqi-icons.py
"""
import argparse
from pathlib import Path

# (name, fill, particle colour, particle count). Order = severity.
CLASSES = [
    ('good',          '#a6e3a1', '#1e1e2e', 0),
    ('moderate',      '#f9e2af', '#1e1e2e', 2),
    ('usg',           '#fab387', '#1e1e2e', 4),
    ('unhealthy',     '#f38ba8', '#1e1e2e', 6),
    ('veryunhealthy', '#cba6f7', '#1e1e2e', 8),
    ('hazardous',     '#7f1d2d', '#f38ba8', 10),
]
OUTLINE = '#1e1e2e'

# Particle positions inside the puff, ordered so earlier ones are spread out.
PARTICLES = [(38, 46), (62, 52), (50, 62), (30, 58), (68, 40), (46, 38),
             (58, 68), (36, 70), (72, 62), (52, 50)]

# Wind-swept puff: a cloud body with two trailing streaks reading as "air".
def puff(fill):
    return f'''<g stroke="{OUTLINE}" stroke-width="3.5" stroke-linejoin="round" stroke-linecap="round">
<path fill="{fill}" d="M20 66 a13 13 0 0 1 7-25 a19 19 0 0 1 36-6 a14 14 0 0 1 14 31 Z"/>
<path fill="none" stroke="{fill}" stroke-width="6" d="M8 78 h34 M50 78 h20 M26 90 h22"/>
</g>'''


def icon(name, fill, pcolor, count):
    dots = ''.join(f'<circle class="p" cx="{x}" cy="{y}" r="5" fill="{pcolor}" opacity=".85"/>'
                   for x, y in PARTICLES[:count])
    return puff(fill) + dots


CSS_HEADER = '''/* Generated by scripts/aqi-icons.py; relative URLs survive install. */
#custom-aqi { background-repeat: no-repeat; background-position: left center;
  background-size: 24px 24px; padding-left: 30px; }
'''


def generate(output):
    output = Path(output)
    (output / 'aqi').mkdir(parents=True, exist_ok=True)
    css = [CSS_HEADER]
    icons = {name: icon(name, fill, pc, n) for name, fill, pc, n in CLASSES}
    icons['nodata'] = (puff('#585b70') +
        '<text x="50" y="60" font-family="sans-serif" font-size="30" font-weight="bold" '
        'fill="#cdd6f4" text-anchor="middle">?</text>')
    for name, body in icons.items():
        svg = (f'<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100" '
               f'viewBox="0 0 100 100">\n<title>aqi: {name}</title>\n{body}\n</svg>\n')
        (output / 'aqi' / f'{name}.svg').write_text(svg)
        css.append(f'#custom-aqi.{name} {{ background-image: url("aqi/{name}.svg"); }}')
    (output / 'aqi.css').write_text('\n'.join(css) + '\n')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output', type=Path, default=Path(__file__).resolve().parents[1] / 'waybar')
    args = parser.parse_args()
    generate(args.output)
    print(f'Generated {len(CLASSES)+1} AQI SVGs and aqi.css in {args.output}')