#!/usr/bin/env python3
"""Generate self-contained lunar SVGs and portable GTK3 CSS (stdlib only).

North-up, Northern Hemisphere: waxing lights the right, waning the left.
120 steps preserve phase shape without network access or a runtime renderer.
Surface markings are hand-drawn approximations, not a photographic map.
"""
import argparse
import math
from pathlib import Path

PHASES = 120

# Broad, low-contrast maria remain legible at 24px. No decorative stars/glow.
SURFACE = '''
<path d="M17 30 Q22 18 32 22 L38 31 Q43 37 35 45 L37 54 Q30 64 22 56 L15 45Z"/>
<path d="M37 24 Q42 17 51 21 Q58 27 53 35 Q43 40 37 32Z"/>
<path d="M55 30 Q61 23 68 28 Q73 34 68 42 L62 44 Q54 41 55 30Z"/>
<path d="M59 45 Q68 37 77 43 L81 52 Q78 60 68 61 Q58 59 56 52Z"/>
<path d="M42 49 Q49 44 55 48 Q62 57 55 63 Q44 65 39 58Z"/>
<path d="M75 31 Q80 27 84 33 L86 41 Q80 44 76 38Z"/>
<ellipse cx="32" cy="67" rx="6" ry="4"/>
'''
CRATERS = '''
<g fill="none" stroke="{rim}" stroke-width="1.25" opacity=".55">
<circle cx="32" cy="46" r="4"/><circle cx="46" cy="76" r="3.2"/>
<circle cx="64" cy="70" r="2.5"/><circle cx="39" cy="15" r="2"/>
<ellipse cx="77" cy="65" rx="2" ry="3"/>
</g>
<g fill="{rim}" opacity=".5"><circle cx="46" cy="76" r="1.3"/>
<circle cx="32" cy="46" r="1.3"/><circle cx="54" cy="66" r="1"/>
<circle cx="59" cy="81" r="1"/><circle cx="26" cy="60" r="1"/></g>
'''


def generate(output):
    output = Path(output)
    (output / 'moon').mkdir(parents=True, exist_ok=True)
    css = ['/* Generated by scripts/moon-icons.py; relative URLs survive install. */',
           '#custom-moon { min-width: 32px; padding: 0; color: transparent;',
           '  background-repeat: no-repeat; background-position: center;',
           '  background-size: 24px 24px;',
           '  background-image: url("moon/phase-000.svg"); }',
           '#custom-moon:hover { background-color: #313244; border-radius: 8px; }']
    for i in range(PHASES):
        angle = 2 * math.pi * i / PHASES
        waxing = i <= PHASES // 2
        side = 1 if waxing else -1
        # Polygon traces the projected sunward limb then elliptical terminator.
        rows = [(-1 + j / 128) for j in range(257)]
        points = [(50 + side * 46 * math.sqrt(max(0, 1-y*y)), 50+46*y) for y in rows]
        points += [(50 + side * math.cos(angle) * 46 * math.sqrt(max(0, 1-y*y)), 50+46*y) for y in reversed(rows)]
        polygon = ' '.join(f'{x:.3f},{y:.3f}' for x,y in points)
        svg = f'''<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100" viewBox="0 0 100 100">
<title>Moon phase {i}/{PHASES}; north up</title>
<defs>
<clipPath id="disc"><circle cx="50" cy="50" r="46"/></clipPath>
<clipPath id="light"><polygon points="{polygon}"/></clipPath>
<radialGradient id="silver" cx="42%" cy="35%" r="70%">
<stop offset="0" stop-color="#f0efea"/><stop offset=".72" stop-color="#d3d6d6"/>
<stop offset="1" stop-color="#9da6b1"/></radialGradient>
</defs>
<g clip-path="url(#disc)">
<circle cx="50" cy="50" r="46" fill="#424856"/>
<g fill="#303642" opacity=".7">{SURFACE}</g>
{CRATERS.format(rim='#687180')}
<g clip-path="url(#light)">
<circle cx="50" cy="50" r="46" fill="url(#silver)"/>
<g fill="#89939b" opacity=".62">{SURFACE}</g>
{CRATERS.format(rim='#fbfaf4')}
</g></g>
<circle cx="50" cy="50" r="46" fill="none" stroke="#a6adbd" stroke-width="3"/>
</svg>'''
        (output / 'moon' / f'phase-{i:03d}.svg').write_text(svg)
        css.append(f'#custom-moon.phase-{i:03d} {{ background-image: url("moon/phase-{i:03d}.svg"); }}')
    (output / 'moon.css').write_text('\n'.join(css) + '\n')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output', type=Path, default=Path(__file__).resolve().parents[1] / 'waybar')
    args = parser.parse_args()
    generate(args.output)
    print(f'Generated {PHASES} moon SVGs and moon.css in {args.output}')
