#!/usr/bin/env python3
"""Generate weather condition SVGs and portable GTK3 CSS (stdlib only).

Palette follows the bar's Catppuccin Mocha; icons are drawn at 100x100 with
high-contrast strokes so silhouettes survive rendering at 24px.
Re-run after editing: python3 scripts/weather-icons.py
"""
import argparse
from pathlib import Path

# Catppuccin Mocha anchors plus weather-specific hues.
SUN_CORE = '#f9e2af'
SUN_EDGE = '#fab387'
CLOUD_LIT = '#cdd6f4'
CLOUD_MID = '#9ca3b8'
CLOUD_DARK = '#7080a0'
RAIN = '#89b4fa'
SNOW = '#dbe4f0'
BOLT = '#f9e2af'
STROKE = '#45475a'

DEFS = f'''<defs>
<radialGradient id="sun" cx="42%" cy="38%" r="65%">
  <stop offset="0" stop-color="{SUN_CORE}"/><stop offset=".75" stop-color="{SUN_CORE}"/>
  <stop offset="1" stop-color="{SUN_EDGE}"/></radialGradient>
<linearGradient id="cloud" x1="0" y1="0" x2="0" y2="1">
  <stop offset="0" stop-color="{CLOUD_LIT}"/><stop offset="1" stop-color="{CLOUD_MID}"/></linearGradient>
</defs>'''

SUN_RAYS = f'''<g stroke="{SUN_EDGE}" stroke-width="7" stroke-linecap="round">
<line x1="50" y1="6" x2="50" y2="18"/><line x1="50" y1="82" x2="50" y2="94"/>
<line x1="6" y1="50" x2="18" y2="50"/><line x1="82" y1="50" x2="94" y2="50"/>
<line x1="19" y1="19" x2="27" y2="27"/><line x1="73" y1="73" x2="81" y2="81"/>
<line x1="81" y1="19" x2="73" y2="27"/><line x1="27" y1="73" x2="19" y2="81"/>
</g>'''

# One soft silver cloud, slightly darker under-belly for volume.
CLOUD = f'''<g stroke="{STROKE}" stroke-width="3" stroke-linejoin="round">
<path fill="url(#cloud)" d="M22 68 a14 14 0 0 1 6-27 a20 20 0 0 1 38-6 a15 15 0 0 1 10 33 Z"/>
</g>
<g fill="{CLOUD_DARK}" opacity=".55"><ellipse cx="44" cy="66" rx="24" ry="4"/></g>'''

# Fluffy multi-bump cloud for coverage states.
CLOUD_BIG = f'''<g stroke="{STROKE}" stroke-width="3" stroke-linejoin="round">
<path fill="url(#cloud)" d="M14 70 a12 12 0 0 1 4-23 a16 16 0 0 1 28-8 a18 18 0 0 1 32 4 a13 13 0 0 1 6 27 Z"/>
</g>
<g fill="{CLOUD_DARK}" opacity=".55"><ellipse cx="46" cy="68" rx="30" ry="4"/></g>'''

RAIN_DROPS = f'''<g stroke="{RAIN}" stroke-width="6" stroke-linecap="round">
<line x1="30" y1="76" x2="26" y2="90"/><line x1="46" y1="76" x2="42" y2="90"/>
<line x1="62" y1="76" x2="58" y2="90"/></g>'''

SNOW_FLAKES = f'''<g stroke="{SNOW}" stroke-width="7" stroke-linecap="round">
<path d="M31 76 v20 M21 86 h20 M24 79 l14 14 M38 79 l-14 14"/>
<path d="M69 76 v20 M59 86 h20 M62 79 l14 14 M76 79 l-14 14"/>
</g>'''

WIND_LINES = f'''<g stroke="{RAIN}" stroke-width="6" stroke-linecap="round" fill="none">
<path d="M10 38 h44 a8 8 0 1 0 -8 -10"/>
<path d="M14 54 h58 a9 9 0 1 1 -9 11"/>
<path d="M10 70 h30"/></g>'''

ICONS = {
    'clear': f'''{DEFS}{SUN_RAYS}<circle cx="50" cy="50" r="26" fill="url(#sun)" stroke="{SUN_EDGE}" stroke-width="2.5"/>''',
    'partly': f'''{DEFS}{SUN_RAYS}<circle cx="38" cy="40" r="20" fill="url(#sun)" stroke="{SUN_EDGE}" stroke-width="2"/>
<g transform="translate(14,20) scale(.78)">{CLOUD}</g>''',
    'cloudy': f'{DEFS}{CLOUD_BIG}',
    'rain': f'{DEFS}{CLOUD}{RAIN_DROPS}',
    'snow': f'{DEFS}{CLOUD}{SNOW_FLAKES}',
    'storm': f'''{DEFS}<g transform="translate(0,-8) scale(1,.92)">{CLOUD}</g><path d="M55 62 l-20 25 h14 l-9 15 27-30 h-14 l12-10 Z" fill="{BOLT}" stroke="#1e1e2e" stroke-width="3" stroke-linejoin="round"/>''',
    'windy': f'{DEFS}{WIND_LINES}',
    # Question-mark card for missing data; muted like the bar's nodata class.
    'nodata': f'''<rect x="26" y="18" width="48" height="64" rx="8" fill="{CLOUD_DARK}" stroke="{STROKE}" stroke-width="3"/>
<text x="50" y="58" font-family="sans-serif" font-size="30" font-weight="bold" fill="{CLOUD_LIT}" text-anchor="middle">?</text>''',
}

CSS_HEADER = '''/* Generated by scripts/weather-icons.py; relative URLs survive install. */
#custom-weather { background-repeat: no-repeat; background-position: left center;
  background-size: 24px 24px; padding-left: 30px; }
'''


def generate(output):
    output = Path(output)
    (output / 'weather').mkdir(parents=True, exist_ok=True)
    css = [CSS_HEADER]
    for name, body in ICONS.items():
        svg = (f'<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100" '
               f'viewBox="0 0 100 100">\n<title>weather: {name}</title>\n{body}\n</svg>\n')
        (output / 'weather' / f'{name}.svg').write_text(svg)
        css.append(f'#custom-weather.{name} {{ background-image: url("weather/{name}.svg"); }}')
    (output / 'weather.css').write_text('\n'.join(css) + '\n')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output', type=Path, default=Path(__file__).resolve().parents[1] / 'waybar')
    args = parser.parse_args()
    generate(args.output)
    print(f'Generated {len(ICONS)} weather SVGs and weather.css in {args.output}')